name: Greetings

on: [pull_request, issues]

jobs:
  greetings:
    name: Greetings

    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |-
            Hello dear new contributor!
            
            Thank you very much for opening your first issue. We will take a look at it very soon!
          pr-message: |-
            Hello dear new contributor!
            
            Thank you very much for submitting your first PR. We will take a look at it very soon!
